journo_fixes = {
    'Kelly Brown, The Eagle Jay Socol, KTSR 92.1': 'Kelly Brown, The Eagle; Jay Socol, KTSR 92.1',
    'Diane Smith, The Brownsville Herald John Burnett, National Public Radio': 'Diane Smith, The Brownsville Herald; John Burnett, National Public Radio',
    'Channel 3, Wichita Falls': 'Channel 3 Wichita Falls',
    'Mike Graczyk': 'Michael Graczyk',
    'Mike Graezyk': 'Michael Graczyk',
    'Mike Gracyzk': 'Michael Graczyk',
    'and Corey Ryan': 'Corey Ryan',
    'Jacque Hilburn, The McKinney Courier': 'Jacque Hilburn, The McKinney Courier-Gazette',
    'Gazette \n        Steve Stoler': 'Steve Stoler',
    'Terry S. Bertling': 'Terry Scott Bertling',
    'Terry Langford': 'Terri Langford',
    'Steward Smith': 'Stewart Smith',
    'Steve SToler': 'Steve Stoler',
    'Sheila Herchkin': 'Sheila Hotchkins',
    'Rosana Ruiz': 'Rosanna Ruiz',
    'Robert Wernsmann': 'Robert Wernsman',
    'Rebecca Mullins': 'Rebecca Mullens',
    'Reba Mullens': 'Rebecca Mullens',
    'Randall Beamer': 'Randy Beamer',
    'Rachel Gleason': 'Rachael Gleason',
    'Pauline Arrillage': 'Pauline Arrillaga',
    'Paula Dietrich': 'Paula Dittrick',
    'Paula Dettrick': 'Paula Dittrick',
    'Michell Lyons': 'Michelle Lyons',
    '  ': ' ',
    'Megan Stacks': 'Megan Stack',
    'Mary Schalangenstein': 'Mary Schlangenstein',
    'Mark Babnieck': 'Mark Babineck',
    'Lisa Tow': 'Lisa Trow',
    'Lisa Sandburg': 'Lisa Sandberg',
    'Leigh-Ann Gideon': 'Leigh-Anne Gideon',
    'L.D. Phillips': 'L.P. Phillips',
    'LP Phillips': 'L.P. Phillips',
    'Ken Molestine': 'Ken Molestina',
    'Karen Wilkison': 'Karen Wilkerson',
    'Juan Luzano': 'Juan Lozano',
    'Juan Lozana': 'Juan Lozano',
    'Jorge Desantiago': 'Jorge DeSantiago',
    'Jorge Enrique DeSantiago': 'Jorge DeSantiago',
    'John Gonzales': 'John Gonzalez',
    'Jay Gorrnley': 'Jay Gormley',
    'Jay Goanley': 'Jay Gormley',
    'Jason Whiteley': 'Jason Whitely',
    'Jason Whitley': 'Jason Whitely',
    'Geoff Drnshel': 'Geoff Drushel',
    'G. L.': 'G.L.',
    'Deon Daughtery': 'Deon Daugherty',
    'Denis Davis': 'Denise Davis',
    'Dale Lozon': 'Dale Lezon',
    'Armando Villsranca': 'Armando Villafranca',
    'Allen Turner': 'Allan Turner',
    'Alan Turner': 'Allan Turner',
    'Associate Press': 'Associated Press',
    'Austin American Statesman': 'Austin American-Statesman',
    'Austin American- Statesman': 'Austin American-Statesman',
    'Bryan College Station Eagle': 'Bryan-College Station Eagle',
    'Bryan Eagle': 'Bryan-College Station Eagle',
    'CBS Channel 11 - Dallas': 'Channel 11 Dallas',
    'CW 33-Dallas': 'CW 33 Dallas',
    'Channel 2 News': 'Channel 2',
    'Channel 2 TV': 'Channel 2',
    'Channel 6 - Beaumont': 'Channel 6 Beaumont',
    'Cleburne Times - Review': 'Cleburne Times-Review',
    'Cleburne Times-Record': 'Cleburne Times-Review',
    'Corpus Christi Caller - Times': 'Corpus Christi Caller-Times',
    'Corpus Christi Caller Times': 'Corpus Christi Caller-Times',
    'Corsicana Sun': 'Corsicana Daily Sun',
    'EFE News Service--Texas Bureau': 'EFE News Service-Texas Bureau',
    'Fort Worth Star - Telegram': 'Fort Worth Star-Telegram',
    'Fort Worth Star Telegram': 'Fort Worth Star-Telegram',
    'Fort Worth-Star Telegram': 'Fort Worth Star-Telegram',
    'Fox 34 News': 'Fox 34',
    'Fox 34-Lubbock': 'Fox 34',
    'Fox 4 in Dallas': 'Fox 4',
    'Hartford Courant - Connecticut': 'Hartford Courant',
    'Jack Magazine-London': 'Jack Magazine',
    'KAMC Channel 28': 'KAMC',
    'KAMC TV': 'KAMC',
    'KAMC-TV': 'KAMC',
    'KAMR TV': 'KAMR',
    'KAMR-TV': 'KAMR',
    'KBMT Channel 12 in Beaumont': 'KBMT',
    'KBTV Channel 4': 'KBTV',
    'KBTX Channel 3': 'KBTX',
    'KBTX TV - Bryan-College Station': 'KBTX',
    'KBTX TV in Bryan': 'KBTX',
    'KBTX-TV': 'KBTX',
    'KBTX-TV - Bryan/College Station': 'KBTX',
    'KCBD - Lubbock': 'KCBD',
    'KCBD TV Lubbock': 'KCBD',
    'KCBD in Lubbock': 'KCBD',
    'KCBD-Lubbock': 'KCBD',
    'KCBD-TV in Lubbock': 'KCBD',
    'KCEN TV': 'KCEN',
    'KCNC TV': 'KCNC',
    'KDFW TV': 'KDFW',
    'KDFW-TV': 'KDFW',
    'KENS Channel 5': 'KENS',
    'KENS TV': 'KENS',
    'KETK - NBC 56': 'KETK',
    'KETK - Region 56': 'KETK',
    'KETK TV': 'KETK',
    'KETK TV in Tyler': 'KETK',
    'KETK-TV in Tyler': 'KETK',
    'KFDA TV': 'KFDA',
    'KFDA-TV': 'KFDA',
    'KFDK - TV 3 Wichita Falls': 'KFDK',
    'KFDM Channel 6 in Beaumont': 'KFDM',
    'KFDM-TV': 'KFDM',
    'KFDX Channel 3': 'KFDX',
    'KFDX TV': 'KFDX',
    'KHOU Channel 11': 'KHOU',
    'KHOU Channel 11 Houston': 'KHOU',
    'KHOU Channel 11-Houston': 'KHOU',
    'KHOU TV': 'KHOU',
    'KHOU TV in Houston': 'KHOU',
    'KHOU TV-Houston': 'KHOU',
    'KHOU-TV - Houston': 'KHOU',
    'KHOU-TV 11': 'KHOU',
    'KIII TV': 'KIII',
    'KIII TV in Corpus Christi': 'KIII',
    'KJAC TV': 'KJAC',
    'KJTV - Lubbock': 'KJTV',
    'KJTV in Lubbock': 'KJTV',
    'KKNX Radio': 'KKNX',
    'KLBJ Radio': 'KLBJ',
    'KLBK Channel 13': 'KLBK',
    'KLBK News-Lubbock': 'KLBK',
    'KLBK in Lubbock': 'KLBK',
    'KLBK/KAMC-TV Lubbock': 'KLBK/KAMC',
    'KLOL Radio': 'KLOL',
    'KLRD Radio': 'KLRD',
    'KLST TV': 'KLST',
    'KLTV - Tyler': 'KLTV',
    'KLTV - Tyler': 'KLTV',
    'KLTV 7 News-Tyler': 'KLTV',
    'KLTV TV': 'KLTV',
    'KLTV in Tyler': 'KLTV',
    'KMOL - Channel 4 San Antonio': 'KMOL',
    'KMOL - San Antonio': 'KMOL',
    'KMOL TV': 'KMOL',
    'KMOL-TV': 'KMOL',
    'KMOO Radio': 'KMOO',
    'KPFT Radio': 'KPFT',
    'KPRC Channel 2': 'KPRC',
    'KPRC Channel 2 Houston': 'KPRC',
    'KPRC TV in Houston': 'KPRC',
    'KPRC-TV Channel 2 in Houston': 'KPRC',
    'KRBC Channel 9': 'KRBC',
    'KRBC TV': 'KRBC',
    'KRBC-TV': 'KRBC',
    'KRGV TV in Weslaco': 'KRGV',
    'KRGV-TV in Harlingen': 'KRGV',
    'KRIS-TV': 'KRIS',
    'KRIV Channel 26': 'KRIV',
    'KRIV TV': 'KRIV',
    'KRIV TV in Houston': 'KRIV',
    'KRIV-TV Houston': 'KRIV',
    'KRLD News Radio': 'KRLD',
    'KRLD News Radio 1080 Dallas': 'KRLD',
    'KRLD Radio': 'KRLD',
    'KSAM Huntsville': 'KSAM',
    'KSAT - San Antonio': 'KSAT',
    'KSAT Channel 12 in San Antonio': 'KSAT',
    'KSAT TV': 'KSAT',
    'KSAT TV San Antonio': 'KSAT',
    'KSHN FM': 'KSHN',
    'KSHN FM 99.9': 'KSHN',
    'KSHU 90.5': 'KSHU',
    'KSHU-FM': 'KSHU',
    'KSLA-TV': 'KSLA',
    'KTAB TV': 'KTAB',
    'KTBC Channel 7': 'KTBC',
    'KTBS TV-3': 'KTBS',
    'KTBS-TV': 'KTBS',
    'KTEN TV': 'KTEN',
    'KTLM TV in Rio Grande Valley': 'KTLM',
    'KTRE TV in Lufkin': 'KTRE',
    'KTRH - Houston': 'KTRH',
    'KTRH News Radio': 'KTRH',
    'KTRH Radio': 'KTRH',
    'KTRH Radio Houston': 'KTRH',
    'KTRH Radio/Houston': 'KTRH',
    'KTRJ Radio': 'KTRJ',
    'KTRK Channel 13': 'KTRK',
    'KTRK TV': 'KTRK',
    'KTRK-TV - Houston': 'KTRK',
    'KTRK-TV Houston': 'KTRK',
    'KTSX TV': 'KTSX',
    'KTVT Channel 11': 'KTVT',
    'KTVT Channel 11 News': 'KTVT',
    'KTVT TV Dallas': 'KTVT',
    'KTVT- CBS 11 Fort Worth': 'KTVT',
    'KTVT-CBS Dallas': 'KTVT',
    'KTVV TV Austin': 'KTVV',
    'KTXS - Abilene': 'KTXS',
    'KTXS Channel 23': 'KTXS',
    'KTXS TV': 'KTXS',
    'KTXS-TV': 'KTXS',
    'KUSA TV': 'KUSA',
    'KVDA Telemundo in San Antonio': 'KVDA',
    'KVDA-TV Telemundo': 'KVDA',
    'KVEO TV in Rio Grande Valley': 'KVEO',
    'KVII - Amarillo': 'KVII',
    'KVII TV': 'KVII',
    'KVII-TV': 'KVII',
    'KVUE TV': 'KVUE',
    'KVUE-TV': 'KVUE',
    'KWEX Univision in San Antonio': 'KWEX',
    'KWTX TV': 'KWTX',
    'KXAN Channel 36': 'KXAN',
    'KXII TV': 'KXII',
    'KXLN TV in Houston': 'KXLN',
    'KXLN Univision Channel 45': 'KXLN',
    'KXLN Univision in Houston': 'KXLN',
    'KXTX TV in Dallas': 'KXTX',
    'KXXV TV': 'KXXV',
    'KXXV-TV': 'KXXV',
    'KXYL - FM Brownwood': 'KXYL',
    'KYTX Channel 19 Longview': 'KYTX',
    'KYTX TV in Tyler': 'KYTX',
    'Kens TV': 'KENS',
    'La Jornada in Mexico City': 'La Jornada',
    'Longview News Journal': 'Longview News-Journal',
    'Lubbock Avalance Journal': 'Lubbock Avalanche-Journal',
    'Lubbock Avalanche Journal': 'Lubbock Avalanche-Journal',
    'Lubbock Avalnche-Journal': 'Lubbock Avalanche-Journal',
    'New 7 - El Paso': 'News 7 El Paso',
    'Notimex-Dallas Bureau': 'Notimex',
    'Palestine Herald County': 'Palestine Herald',
    'Palestine Herald Press': 'Palestine Herald',
    'Portland News Texas': 'Portland Texas News',
    'SHSU Cable Channel 7': 'SHSU',
    'SHSU Channel 7': 'SHSU',
    'San Antonio Express - News': 'San Antonio Express-News',
    'San Antonio Express News': 'San Antonio Express-News',
    'Semana News in Houston': 'Semana News',
    'Star Telegram': 'Fort Worth Star-Telegram',
    'Telemundo 40 in McAllen': 'Telemundo 40 McAllen',
    'Telemundo KTMB': 'KTMB',
    'Telemundo KVDA': 'KVDA',
    'Telemundo Network': 'Telemundo',
    'Telemundo in San Antonio': 'Telemundo San Antonio',
    'Televisa Network in Houston': 'Televisa Network Houston',
    'The Boston Globe Austin Bureau': 'The Boston Globe',
    'The Bryan College Station Eagle': 'Bryan-College Station Eagle',
    'The Bryan Eagle': 'Bryan-College Station Eagle',
    'The Bryan-College Station Eagle': 'Bryan-College Station Eagle',
    'The Dallas Morning News': 'Dallas Morning News',
    'The Denton Record': 'Denton Record',
    'The Eagle': 'Bryan-College Station Eagle',
    'The Eagle Bryan-College Station': 'Bryan-College Station Eagle',
    'The Galveston County Daily News': 'Galveston County Daily News',
    'The Houston Chronicle': 'Houston Chronicle',
    'The Houston Press': 'Houston Press',
    'The Houstonian': 'Houstonian',
    'The Huntsville Item': 'Huntsville Item',
    'The Longview News Journal': 'Longview News-Journal',
    'The Messenger in Grapeland': 'The Grapeland Messenger',
    'The Monitor - McAllen': 'The McAllen Monitor',
    'The Monitor in McAllan': 'The McAllen Monitor',
    'The Paris News': 'The Paris Texas News',
    'The Paris News Texas': 'The Paris Texas News',
    'The San Antonio Express': 'San Antonio Express-News',
    'The San Antonio Express-News': 'San Antonio Express-News',
    'The Tyler Morning Telegraph': 'Tyler Morning Telegraph',
    'Tyler Courier Times Telegraph': 'Tyler Morning Telegraph',
    'Tyler Morning Telegram': 'Tyler Morning Telegraph',
    'US New and World Report': 'U.S. News and World Report',
    'Univision 45 in Houston': 'Univision 45 Houston',
    'Univision Channel 23 Dallas': 'Univision 23 Dallas',
    'Univision KWEX': 'KWEX',
    'Univision KXLN': 'KXLN',
    'Univision in Dallas': 'Univision Dallas',
    'Univision in San Antonio': 'Univision San Antonio',
    'WAOI-TV': 'WAOI',
    'WBAP Radio': 'WBAP',
    'WFAA - Channel 8': 'WFAA',
    'WFAA Channel 8 Dallas': 'WFAA',
    'WFAA Channel 8-Dallas': 'WFAA',
    'WFAA TV': 'WFAA',
    'WFAA TV Dallas': 'WFAA',
    'WFAA TV in Dallas': 'WFAA',
    'WFAA Television': 'WFAA',
    'WFAA Dallas': 'WFAA',
    'WFAA in Dallas': 'WFAA',
    'WFAA-Dallas': 'WFAA',
    'WFAA-TV': 'WFAA',
    'WOAI Channel 4': 'WOAI',
    'WOAI Channel 4 in San Antonio': 'WOAI',
    'WOAI Channel 4-San Antonio': 'WOAI',
    'WOAI Radio': 'WOAI',
    'WOAI TX San Antonio': 'WOAI',
    'WOAI-TV': 'WOAI',
    'WOAI in San Antonio': 'WOAI',
    'WOAI-San Antonio': 'WOAI',
    'WTAW Radio': 'WTAW',
    'Waco Tribune Herald': 'Waco Tribune-Herald',
    'Wichita Falls Times News Record': 'Wichita Falls Times-Record-News',
    'Wichita Falls Times Record News': 'Wichita Falls Times-Record-News',
    'KFDK - TV 3 Wichita Falls': 'KFDK',
    'KFDX TV, Wichita Falls': 'KFDX',
    'KTVT News': 'KTVT',
    'KTSR 92.1': 'KTSR',
    'KTRH Houston': 'KTRH',
    'KTRH/Houston': 'KTRH'
}
